### ISSUE TITLE
Matlab code final results are unfamiliar

### ISSUE THREAD

**Issue by woensug-choi** [Field-Robotics-Lab/matlab_sonar_prototype#2]
@kerednoslo 
I was unable to see the final results you have shared on email with uploaded codes. I've made a push with some modifications to use pre-saved sphereModel.mat file. Could you give it a look?

The code you provide is much faster when imported to the plugin! I need to polish it more and double check the intermediate values with your code.

**Comment by kerednoslo** [comment]
@woensug-choi 
Glad it's faster! I have made a few modifications in [this commit](https://github.com/Field-Robotics-Lab/matlab_sonar_prototype/commit/3f1cc0ef2cdf16931537672679c186cae73f8b40).

**Comment by kerednoslo** [comment]
@woensug-choi 
I have a third method that does not use an FFT in the loop. It incoherently (using rms average for pressure) adds up all scatterers that fall in the same time sample, and then does an FFT and IFFT after the scatterers have been added up to give the correct time sidelobes, then incorporates the beam sidelobes in the same way as method 2. This **should** be faster than method 3, but is about the same in the Matlab version. This might be because Matlab is very slow at loops, or the problem isn't big enough to see the gains.

I put an initial version in the Matlab code, in [this commit](https://github.com/Field-Robotics-Lab/matlab_sonar_prototype/commit/62129b5172b92b1f43ca7bbed0a1ac2d9d3b8eb7)

Best,
Derek
